version: "3.9"

services:
  mongo-main:
    image: mongo:latest
    container_name: mongo-main
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-test:
    image: mongo:latest
    container_name: mongo-test
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db

  dime:
    build: .
    restart: unless-stopped
    environment:
      MONGO_HOST: "mongo-main:27017"
      MONGO_TEST_HOST: "mongo-test:27017"
    ports:
      - "1323:1323"


volumes:
  mongo_data:
  mongo_test_data:
