package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"
	"dime/graph/model"
	"fmt"
)

// GetUser is the resolver for the GetUser field.
func (r *queryResolver) GetUser(ctx context.Context) (*model.User, error) {
	return &model.User{
		FirstName: "hi",
		LastName:  "joe",
	}, nil
	//panic(fmt.Errorf("not implemented: GetUser - GetUser"))
}

// GetTransactions is the resolver for the GetTransactions field.
func (r *queryResolver) GetTransactions(ctx context.Context, userID string) ([]*model.Transaction, error) {
	panic(fmt.Errorf("not implemented: GetTransactions - GetTransactions"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
