version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-test:
    image: mongo:latest
    container_name: mongo-test
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_data:
  mongo_test_data:
