name: MongoDB and Go Test

on: [push, pull_request]

jobs:
  test:
    name: MongoDB and Go Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017
        options: >-
          --health-cmd 'mongo --quiet --eval "printjson(db.serverStatus())"' --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Start MongoDB
        run: docker-compose up -d

      - name: Wait for MongoDB to start
        run: docker-compose exec mongodb bash -c 'while ! mongo --eval "print(\"waited for connection\")"; do sleep 1; done'

      - name: Run tests
        run: go test ./...
